### ISSUE TITLE
Don't hardcode the hadithText attribute in code

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#21]

**Comment by andryanduta** [comment]
hi @hasankhan, I'm interested for this, can you help to elaborate the issue? 
anyway I found some typo here (hadtihs -> hadiths?), maybe we can fix it as well? cmiiw
1. https://github.com/sunnah-com/corrections/blob/b185da511983bf37e057aa93f011ec5414493406/frontend/main.py#L121
2. https://github.com/sunnah-com/corrections/blob/b185da511983bf37e057aa93f011ec5414493406/frontend/static/js/app.js#L92

**Comment by hasankhan** [comment]
Yes, let's fixed the spellings as well. Can you please send a pull request for it first separately?

The code currently assumes that the correction only applies to hadithText attribute. We want to make the code generic such that it works for any attribute of the hadith. We're currently doing this for adding support for adjusting hadith grade.

When rendering correction, if we have the grade specified as the attribute we will show it on the UI in the correction area instead of showing the body. where the original hadith is loaded, there we will show the body as well as the grade regardless what the correction was. 

then we need to update the python code to update the table based on the attribute being corrected rather than assuming it must be headithText
