### ISSUE TITLE
add a checkbox at the bottom of the correction view that is used to inform the submitter via email

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#26]
when we select the checkbox the submitter would be sent an email and informed that their submission is corrected or rejected.
We will show a comment section that is pre-filled with a template response that can be edited by the moderator to give an explanation of why.

**Comment by devil-cyber** [comment]
Hey , i want to work on this issue and project, here after seeing your linkedin post😀

**Comment by hasankhan** [comment]
#41 class to send an email

**Comment by ilyas-shah** [comment]
I will be working on this. I have set up the local frontend app.

I will provide the ETA after having a discussion with @hasankhan
