### ISSUE TITLE
create a class that can manage users in aws cognito users pool

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#32]
this class should allow adding a new user, removing a user, resetting their password

**Comment by Ysajid** [comment]
I would like to pick this up inshaAllah

**Comment by Ysajid** [comment]
Assalamu alaikum brother @hasankhan, since we'll need to run tests for these, is it better to use the [localstack](https://localstack.cloud/) docker image instead of individual images for the services (i.e. dynamodb, cognito)?

**Comment by hasankhan** [comment]
Walaikum Assalam wa rehmatuAllahi wa baraktuhu

cognito is only available in pro version of localstack and I'd like to avoid adding more layers of abstraction. Let's stick to what we have at the moment. We can revisit later insha'Allah.

**Comment by Ysajid** [comment]
> cognito is only available in pro version of localstack and I'd like to avoid adding more layers of abstraction. Let's stick to what we have at the moment. We can revisit later insha'Allah.

In that case, can you give an idea of how we will mock Cognito in tests?

**Comment by hasankhan** [comment]
Wrap the usage in a class and mock out the class.
