### ISSUE TITLE
write a user manager class that uses aws cognito and dynamodb users class

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#33]
write a class that will wrap #32 and #30 and will be used to create a new user by adding it to both aws cognito as well as dynamodb, same for deleting, updating and listing users.

please also add unit tests

**Comment by Ysajid** [comment]
Assalamu alaikum, since both #32 and #30 are done now, I would like to pick this one up inshaAllah.

**Comment by hasankhan** [comment]
Walaikum Assalam wa rehmatuAllahi wa baraktuhu

JazakAllah khair

**Comment by hasankhan** [comment]
@Ysajid is there any update on this?

**Comment by Ysajid** [comment]
I did some work but got stuck with a problem. There are some differences between how cognito and dynamodb handles users CRUD. I'll check and inform you inshaAllah.
