### ISSUE TITLE
Write a class that can read the archive records from dynamodb

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#37]
This class should return N number of records at a time with the option to page the results. Update the existing code to use this new class for adding records to archive table.

**Comment by Ysajid** [comment]
Assalamu alaikum brother @hasankhan, I can pick this one up. I will try to deliver by next Sunday.  
Also, this will also be used for writing to the db right?

**Comment by hasankhan** [comment]
Walaikum Assalam wa rehmatuAllahi wa baraktuhu

yes, we will update the existing code to use this clas to write to DB as well. Can you please add a unit test for this as well?

**Comment by Ysajid** [comment]
Ok sure, I'll write tests as well inshaAllah.
