### ISSUE TITLE
write a class that can send an email 

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#41]
import whatever 3rd party library necessary for us to be able to email the person who submitted the correction. The class can have a method called sendEmail() or email() that takes in the user email address, the subject, and a body and sends the email.

**Comment by businessglitch** [comment]
I will be working on this. Will setup the env locally this weekend and update with and ETA.

**Comment by businessglitch** [comment]
I will have a Pull request ready by Sunday EOD. 

Code base will include:
- **Email** class that leverages flask_mail (gmail server)
- Tests for **Email** class
- Code factorization

Additional research would be done for sending templated emails.

**Comment by hasankhan** [comment]
gmail server is for testing right? I would expect the class to be able to send via any smtp server.

**Comment by businessglitch** [comment]
My apologies, for clarification I meant smtp's gmail server address.  
`MAIL_SERVER = 'smtp.gmail.com'`

**Comment by businessglitch** [comment]
That is correct, gmail if for testing.
