### ISSUE TITLE
Integrate with travis ci to automate running unit tests for each pull request and commit

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#44]

**Comment by tanjinP** [comment]
@hasankhan are you taking any contributors? I have some experience in CI/CD so I can help with this in sha Allah.

Quick Qs:
- don't see any existing tests, are you thinking about adding them in frontend or backend or both? Can include a sample one in an upcoming PR for this issue.
- why not use [GitHub Actions](https://github.com/features/actions) - while still a new compared to Travis it does have better integration with GitHub as everything is in one place.

**Comment by hasankhan** [comment]
@tanjinP yes contributions are welcome. JazakAllah khair

I'm unfamiliar with Github actions. If it is free then sure, we can use that instead. Yes, there aren't any tests yet. We have a task for that. For now, the CI infra can ensure that we're able to build the container and run it successfully.
