### ISSUE TITLE
Write the correction to the hadith database on approval

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#5]
- We will write the correction directly to sunnah.com backend database
- The details of the table e.g. server, username, password, table name, etc should be in config

**Comment by ahadith** [comment]
Take the database name from a config file. It is a MySQL database. Assume a generic table name like `english_hadith_table`, (or `arabic_hadith_table` or `urdu_hadith_table` depending on the language), update the `hadithText` attribute for the `englishURN` (or arabicURN or urduURN respectively) attribute.
