### ISSUE TITLE
Populate text box with email template when the user clicks "Add Message"

### ISSUE THREAD

**Issue by ahadith** [sunnah-com/corrections#64]
Get the current email template from the file, put it in the text box, allow for modifications, and use the custom text in the email to be sent.

**Comment by hasankhan** [comment]
moderator comment is placed inside the template at a position where the reason for moderation action is supposed to go. This makes the template consistent while allowing the moderator to add a custom comment as a reason. 

What do we gain by allowing the moderator to change the template?

**Comment by ahadith** [comment]
The templates are not available to the end users so they don't know how their comments will fit into the whole email and it makes it difficult to write and send something that reads well (instead of reading disjointedly).

**Comment by hasankhan** [comment]
done
