### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#68]
![image](https://user-images.githubusercontent.com/1337072/111911479-0e19ea80-8a23-11eb-8588-cec4ed38819f.png)

- Text boxes are uneven in size
- Scrollbar isn't looking good on the left
- The queue dropdown on the top is too close to the textbox
- The "move to" dropdown opens at a weird location.
- The top navigation bar doesn't look good
- Logout button is not consistent with the navigation buttons or action buttons at the bottom
- The entire UI needs a new design.

We want to keep the three-column layout, preview at the bottom, and action buttons in a separate section. Everything else can be formatted/designed/structured differently.

**Comment by ahmadpx** [comment]
@hasankhan which option do you prefer ?
https://www.figma.com/file/7h1QKXYnt0UMvaFPyYDLPs/Hadith-Correction-App?node-id=0%3A1

**Comment by hasankhan** [comment]
The left one is great. jazakAllah khair.

**Comment by hasankhan** [comment]
@sunnixx can you please coordinate with br. @ahmadpx on this. You can distribute the work so there isn't wasted effort or conflicting changes.

**Comment by hasankhan** [comment]
* The success and error messages need to be improved.
* The preview box stays on the screen while hadith is loading

**Comment by businessglitch** [comment]
Salaam @hasankhan  Please assign the issue to me. Will have the UI look like the left one on these UI's made by @ahmadpx 
 https://www.figma.com/file/7h1QKXYnt0UMvaFPyYDLPs/Hadith-Correction-App?node-id=0%3A1

**Comment by businessglitch** [comment]
Will start working on this after 26th and will get it done over the weekend!

**Comment by hasankhan** [comment]
Sounds good. Thank you!

**Comment by businessglitch** [comment]
@hasankhan Is there anything else you feel like that can be improved?

**Comment by hasankhan** [comment]
I just got a chance to test the UI and it seems to be jumping a lot when approving and rejecting items. Can you please take a look and ensure visibility of items doesn't cause UI to go up and down?

The loading progress bar size can be reduced and it can show in the same place where success/failure messages are shown. They can be given a dedicated place so UI won't move with their appearnce.

**Comment by hasankhan** [comment]
This is fixed.
