### ISSUE TITLE
Create a ui for showing correction fetched asynchronously

### ISSUE THREAD

**Issue by hasankhan** [sunnah-com/corrections#8]
- Should have hadith displayed next to it
- hadith will be fetched asynchronously
- show the original and modified text
- highlight the changes in the modified text (use some text diff library to figure out what to highlight)
- allow changing the modified text
- add reject or approve button

**Comment by Ysajid** [comment]
Assalamu alaikum brother @hasankhan, I think I can start with this first. If there is a UI, we can easily test the other features inshaAllah. I need some clarifications though

1. Do we need to use some frontend framework or library? What do you have in mind?
2. Will we show all the correction requests in one page or seperate pages for collections/books etc?
3. For calculating and highlighting the diffs, we can use google's [diff-match-patch](https://github.com/google/diff-match-patch/wiki/Language:-JavaScript) I think.

**Comment by hasankhan** [comment]
Walaikum Assalam, jazakAllah khair!

* We can use Vue framework for showing the correction.
* We will show single correction at a time. I've added an API call to fetch single correction. 
* We only allow correction against hadithText attribute so we're not doing correction for collection/book.
