### ISSUE TITLE
Trying to make contributions and learn on the journey...

### ISSUE THREAD

**Issue by Ellhassan213** [sunnah-com/corrections#83]
Salam,

My name is Lawal Hassan.

Long story short, I have a background in mainly Engineering and a bit of Software. I am currently trying to pursue and lean more towards Software. I have recently completed the Fullstack Web Developer course on Udacity.

I thought in sha Allah if I reach out, I will be able to contribute to your platforms, gaining more practical experience. Hopefully both parties benefit in sha Allah.

Regards,
Lawal

**Comment by hasankhan** [comment]
Walaikum Assalam wa rehmatuAllahi wa baraktuhu

Please pick an issue you're interested in contributing to and we can discuss how to proceed further. You can also reach out to me on https://www.linkedin.com/in/hasankhan/
